# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for javascript
  - package-ecosystem: "javascript"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for Python
  - package-ecosystem: "python"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
